services:
  - type: web
    name: qr-attendance-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: qr-attendance-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: qr-attendance-db
    databaseName: qr_attendance
    user: qr_user